services:
  postgres:
    image: postgres:17
    container_name: uaimed_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: uaimed
    ports:
      - "5432:5432"
    volumes:
      # Cria automaticamente o banco uaimed_test ao iniciar o container
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

